site_name: Donda

nav:
  - Home: index.md

  - Analises:
    - Home: analises/index.md
    # --- analises devem vir desde ponto em diante com titulo e caminho do arquivo

  - Projetos:
    - Home: index.md
    # --- projetos devem vir desde ponto em diante com titulo e caminho do arquivo

theme:
  name: mkdocs
  include_sidebar: true

markdown_extensions:
  - toc:
      permalink: "#"
      title: "Table of Contents"
      baselevel: 2